# Generated by Django 4.1.2 on 2023-03-05 20:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_options_alter_note_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
    ]
